
name : Name_whatever_you_want

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch

  push:
    branches:
      - master
  
#A workflow run is made up of one or more jobs. Jobs run in parallel by default. 

jobs:
    # Here job is to build the app

    build:
        #The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
 

    runs-on: ubuntu-latest

        #A job contains a sequence of tasks called steps. Steps can run commands, run setup tasks, or run an action in your repository, a public repository, or an action 

    name: Deploying to surge
    steps:
            #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

            - uses: actions/checkout@v2

            #This action sets by node environment for use in actions.A beta release of Node which adds reliability for pulling node distributions.

            - name: Install Node.js
              uses: actions/setup-node@v2-beta
              with:
                   node-version: 12
                
            # Yarn Installation

            - name: Prepare for Yarn Installation
              run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - name: install yarn
              run: sudo apt update && sudo apt install yarn
            - name: Install Packages
              run: yarn install
            - name: Build React App
              run: yarn build

            # Deploying on Surge

            - name: Install Surge
              run: npm install -g surge
            - name: Run surge
              run: surge ./build https://practice_react_app.surge.sh/ --token ${{ secrets.react_secret }}


